import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { Toaster } from "sonner"
import Footer from "./_components/footer"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen justify-center antialiased`}
      >
        <div className="w-[375px] max-w-full items-center overflow-hidden rounded-xl border border-zinc-700 shadow-lg">
          {children}
          <Toaster />
          <Footer />
        </div>
      </body>
    </html>
  )
}

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html lang="en" className="dark">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen items-center justify-center bg-zinc-900 text-white antialiased`}
//       >
//         <div className="w-[375px] max-w-full overflow-hidden rounded-xl border border-zinc-700 shadow-lg">
//           {children}
//         </div>
//       </body>
//     </html>
//   )
// }
